<template>
 <div class="features container is-fluid">
     FEATURESFEATURESFEATURESFEATURESFEATURESFEATURESFEATURESFEATURES
     FEATURESFEATURESFEATURESFEATURESFEATURESFEATURESFEATURESFEATURES
     FEATURESFEATURESFEATURESFEATURESFEATURESFEATURESFEATURESFEATURES
</div>
</template>

<script>
export default {
  name: 'features-content'
}
</script>